name       : grilo
version    : 0.3.4
release    : 14
source     :
    - https://download.gnome.org/sources/grilo/0.3/grilo-0.3.4.tar.xz : 7c6964053b42574c2f14715d2392a02ea5cbace955eb73e067c77aa3e43b066e
license    : LGPL-2.0
component  : desktop.gnome.core
summary    : Media discovery framework
description: |
    Grilo is a framework focused on making media discovery and browsing easy for application developers.

    More precisely, Grilo provides:

    A single, high-level API that abstracts the differences among various media content providers, allowing application developers to integrate content from various services and sources easily.
    A collection of plugins for accessing content from various media providers. Developers can share efforts and code by writing plugins for the framework that are application agnostic.
    A flexible API that allows plugin developers to write plugins of various kinds.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(oauth)
    - pkgconfig(totem-plparser)
    - vala
setup      : |
    %configure --disable-static \
               --enable-grl-net \
               --enable-grl-pls \
               --enable-introspection \
               --enable-vala
build      : |
    %make
install    : |
    %make_install
