name        : grilo
version     : 0.2.14
release     : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/grilo/0.2/grilo-0.2.14.tar.xz : 79c82ea1747ae7430a648aa9660e44d88d48c968bcdaeb3b2c5cb97e1c921ccd
license     :
    - LGPL-2.0
summary     : Media discovery framework
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(totem-plparser)
    - pkgconfig(oauth)
    - pkgconfig(libsoup-2.4)
    - vala
description : |
    Grilo is a framework focused on making media discovery and browsing easy for application developers.
    
    More precisely, Grilo provides:
    
    A single, high-level API that abstracts the differences among various media content providers, allowing application developers to integrate content from various services and sources easily.
    A collection of plugins for accessing content from various media providers. Developers can share efforts and code by writing plugins for the framework that are application agnostic.
    A flexible API that allows plugin developers to write plugins of various kinds.
    
setup      : |
    %configure --disable-static \
               --enable-introspection \
               --enable-vala \
               --enable-grl-pls \
               --enable-grl-net
build      : |
    %make
install    : |
    %make_install
