name       : grilo
version    : 0.3.13
release    : 25
source     :
    - https://download.gnome.org/sources/grilo/0.3/grilo-0.3.13.tar.xz : d14837f22341943ed8a189d9f0827a17016b802d18d0ed080e1413de0fdc927b
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : Media discovery framework
description: |
    Grilo is a framework focused on making media discovery and browsing easy for application developers.

    More precisely, Grilo provides:

    A single, high-level API that abstracts the differences among various media content providers, allowing application developers to integrate content from various services and sources easily.
    A collection of plugins for accessing content from various media providers. Developers can share efforts and code by writing plugins for the framework that are application agnostic.
    A flexible API that allows plugin developers to write plugins of various kinds.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(oauth)
    - pkgconfig(totem-plparser)
    - vala
setup      : |
    %meson_configure -Denable-gtk-doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
