name        : grilo
version     : 0.2.15
release     : 10
source     :
    - http://ftp.gnome.org/pub/gnome/sources/grilo/0.2/grilo-0.2.15.tar.xz : 6f5d2583250a68e76d281edaa08adb880d5a78ed46f9ecd22ae4715f1dd66815
license     :
    - LGPL-2.0
summary     : Media discovery framework
description : |
    Grilo is a framework focused on making media discovery and browsing easy for application developers.
    
    More precisely, Grilo provides:
    
    A single, high-level API that abstracts the differences among various media content providers, allowing application developers to integrate content from various services and sources easily.
    A collection of plugins for accessing content from various media providers. Developers can share efforts and code by writing plugins for the framework that are application agnostic.
    A flexible API that allows plugin developers to write plugins of various kinds.
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(totem-plparser)
    - pkgconfig(oauth)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %configure --disable-static \
               --enable-introspection \
               --enable-vala \
               --enable-grl-pls \
               --enable-grl-net
build      : |
    %make
install    : |
    %make_install
