name       : grilo
version    : 0.3.15
release    : 33
source     :
    - https://download.gnome.org/sources/grilo/0.3/grilo-0.3.15.tar.xz : f352acf73665669934270636fede66b52da6801fe20f638c4048ab2678577b2d
homepage   : https://gitlab.gnome.org/GNOME/grilo
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : Media discovery framework
description: |
    Grilo is a framework focused on making media discovery and browsing easy for application developers.

    More precisely, Grilo provides:

    A single, high-level API that abstracts the differences among various media content providers, allowing application developers to integrate content from various services and sources easily.
    A collection of plugins for accessing content from various media providers. Developers can share efforts and code by writing plugins for the framework that are application agnostic.
    A flexible API that allows plugin developers to write plugins of various kinds.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(oauth)
    - pkgconfig(totem-plparser)
    - vala
setup      : |
    %meson_configure -Denable-gtk-doc=false -Dsoup3=false
build      : |
    %ninja_build
install    : |
    %ninja_install
